# Generated by Django 3.2.16 on 2023-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('type', models.CharField(choices=[('Personal', 'Personal'), ('Company', 'Company')], default='Personal', max_length=100, verbose_name='type')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phonde_number_1', models.CharField(max_length=100, verbose_name='phone number')),
                ('phonde_number_2', models.CharField(max_length=100, verbose_name='phone number')),
                ('address', models.TextField()),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
