# Generated by Django 3.2.16 on 2023-02-04 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_installment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='contract starting date'),
        ),
    ]
