# Generated by Django 3.2.16 on 2023-02-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
