# Generated by Django 3.2.16 on 2023-02-12 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_auto_20230212_1559'),
        ('contract', '0004_auto_20230212_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='balance')),
                ('operation_style', models.CharField(blank=True, choices=[('INCOME', 'INCOME'), ('EXPENSE', 'EXPENSE')], default=None, max_length=100, null=True, verbose_name='operation_style')),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='quantity')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='contract.customer')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flows', to='company.office')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_personals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='company name')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='balance')),
                ('office', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cashbox', to='company.office')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
