# Generated by Django 3.2.16 on 2023-02-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20230212_1559'),
        ('product', '0001_initial'),
        ('contract', '0004_auto_20230212_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='discount'),
        ),
        migrations.AddField(
            model_name='contract',
            name='office',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='company.office'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='product_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contract',
            name='remaining_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='remaining payment'),
        ),
        migrations.AddField(
            model_name='contract',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='total amount'),
        ),
    ]
